name: Check for goodlock updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - device: "SM-G998B"
            sdk: "31"
            os: "12"
          - device: "SM-N985F"
            sdk: "30"
            os: "11"
          - device: "SM-N985F"
            sdk: "29"
            os: "10"
          - device: "SM-G965F"
            sdk: "28"
            os: "9"

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check for update
        id: check
        run: |
          need_update=0
          curl --retry 5 --retry-delay 5 "http://vas.samsungapps.com/product/getContentCategoryProductList.as?contentCategoryID=0000005309&deviceId=${{ matrix.device }}&sdkVer=${{ matrix.sdk }}&mcc=262&mnc=01&csc=DBT&imgWidth=512&imgHeight=512&startNum=1&endNum=100&alignOrder=recent&callerId=com.samsung.android.goodlock&cc=NONE" > tmp-${{ matrix.os }}.xml
          if [ "$(diff tmp-${{ matrix.os }}.xml orig_goodlock${{ matrix.os }}.xml)" != "" ]; then need_update=1; fi
          echo ::set-output name=need_update::$need_update

      - name: Update current version
        if: steps.check.outputs.need_update == 1
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin ${{github.ref}} --ff-only
          curl --retry 5 --retry-delay 5 "http://vas.samsungapps.com/product/getContentCategoryProductList.as?contentCategoryID=0000005309&deviceId=${{ matrix.device }}&sdkVer=${{ matrix.sdk }}&mcc=262&mnc=01&csc=DBT&imgWidth=512&imgHeight=512&startNum=1&endNum=100&alignOrder=recent&callerId=com.samsung.android.goodlock&cc=NONE" > orig_goodlock${{ matrix.os }}.xml
          git add orig_goodlock${{ matrix.os }}.xml
          git commit -m "orig_goodlock${{ matrix.os }}: update of $(date +'%d-%m-%Y %H:%M')"

      - name: Push changes to repo
        if: steps.check.outputs.need_update == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
